### ISSUE TITLE
Update fail since issue #25 fix

### ISSUE THREAD

**Issue by HerveEmagma** [Sylius/SyliusThemeBundle#26]
Since last fix, when I want to update my Sylius project with composer, there is an error when I clear cache :

`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Symfony\Component\Translation\LoggingTranslator::__construct() must implement interface Symfony\Component\Translation\TranslatorInterface, instance of Sylius\Bundle\ThemeBundle\Translation\ThemeAwareTranslator given, called in /apps/sylius/var/cache/dev/ContainerO9zxhet/srcDevDebugProjectContainer.php on line 5618 in /apps/sylius/vendor/symfony/symfony/src/Symfony/Component/Translation/LoggingTranslator.php:33
`
It seems that there is no compatibility check between versions of symfony, and that the minimum version required is 4.2.7.
To fix it, I have to add conflict on my composer.json

`    "conflict": {
        "sylius/theme-bundle": "1.4.5"
    },`

https://github.com/Sylius/SyliusThemeBundle/commit/a276246c4c795dd4935463caac6a722082b0737e

Thanks !

**Comment by HerveEmagma** [comment]
Details : I found I was blocked on Symfony 3.4 by a plugin

**Comment by ostrolucky** [comment]
Experiencing same issue when migrating to sylius 1.3.x on Symfony 3.4 application
